src/Arcus.Security.All/Arcus.Security.All.csproj, src/Arcus.Security.All/README.md, src/Arcus.Security.sln
=> Provide empty boilerplate

src/Arcus.Security.All/Arcus.Security.All.csproj, src/Arcus.Security.Core/Arcus.Security.Core.csproj, src/Arcus.Security.Core/Exceptions/SecretNotFoundException.cs, src/Arcus.Security.Core/ISecretProvider.cs, src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj, src/Arcus.Security.Tests.Unit/Core/SecretNotFoundExceptionTests.cs, src/Arcus.Security.sln
Created `ISecretProvider` and `KeyNotFoundException`
=> Arcus.Security.Core

.gitignore, src/Arcus.Security.Tests.Integration/Arcus.Security.Tests.Integration.csproj, src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs, src/Arcus.Security.Tests.Integration/appsettings.json
Fix appsettings.json configuration for integration tests (update gitignore and allow to override locally).  
This is related to #38
=> Integration tests

src/Arcus.Security.Core/Arcus.Security.Core.csproj, src/Arcus.Security.KeyVault/Arcus.Security.KeyVault.csproj
=> Generate NuGet packages on build

deploy/arm/deploy-testing-infrastructure.json, deploy/arm/deploy-testing-infrastructure.parameters.json
=> added arm template for arcus test key vault

src/Arcus.Security.Core/Arcus.Security.Core.csproj, src/Arcus.Security.Core/Caching/Configuration/CacheConfiguration.cs, src/Arcus.Security.Core/Caching/Configuration/Interfaces/ICacheConfiguration.cs, src/Arcus.Security.Secrets.Core/Caching/CachedSecretProvider.cs, src/Arcus.Security.Secrets.Core/Caching/SecretProviderCachingExtensions.cs, src/Arcus.Security.Tests.Unit/Core/CachedSecretProviderTests.cs, src/Arcus.Security.sln
Introduce ICacheConfiguration to make future changes easier.
Relates to #8
=> Introduce ICacheConfiguration

README.md
Provide NuGet badge in README.
Closes #1
=> Provide NuGet badge

README.md, docs/auth/azure-key-vault.md, docs/features/secrets/consume-from-key-vault.md, docs/features/secrets/general.md, docs/index.md, src/Arcus.Security.Tests.Unit/KeyVault/Configuration/KeyVaultConfigurationTests.cs
Provide documentation on how to consume secrets and how to authenticate.
This is the last piece of our v0.1 release.
Closes #44, #7 & #8.
=> Provide documentation how to consume secrets

docs/features/secrets/general.md, src/Arcus.Security.Providers.AzureKeyVault/Authentication/CertificateBasedAuthentication.cs, src/Arcus.Security.Providers.AzureKeyVault/Authentication/Interfaces/IKeyVaultAuthentication.cs, src/Arcus.Security.Providers.AzureKeyVault/Authentication/ManagedServiceIdentityAuthenticator.cs, src/Arcus.Security.Providers.AzureKeyVault/Authentication/ServicePrincipalAuthenticator.cs, src/Arcus.Security.Secrets.AzureKeyVault/CompatibleKeyVaultAuthentication.cs, src/Arcus.Security.Secrets.AzureKeyVault/KeyVaultSecretProvider.cs, src/Arcus.Security.Secrets.Core/Caching/CachedSecretProvider.cs, src/Arcus.Security.Secrets.Core/Interfaces/ICachedSecretProvider.cs, src/Arcus.Security.Secrets.Core/Interfaces/ISecretProvider.cs, src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs, src/Arcus.Security.Tests.Unit/Core/CachedSecretProviderTests.cs, src/Arcus.Security.Tests.Unit/Core/Stubs/TestSecretProviderStub.cs, src/Arcus.Security.Tests.Unit/KeyVault/Doubles/AzureKeyVaultAuthenticatorDummy.cs, src/Arcus.Security.Tests.Unit/KeyVault/Doubles/StubKeyVaultAuthenticator.cs, src/Arcus.Security.Tests.Unit/KeyVault/KeyVaultSecretProviderTests.cs
=> REFACTOR: suffix async methods with '...Async'

docs/README.md, docs/guides/running-integration-tests.md
Describe how the integration tests can be run with the ARM template and
environment variables.
Closes #66
=> DOC: running integration tests

docs/auth/azure-key-vault.md, docs/features/key-vault/extensions/iconfiguration-integration.md, docs/features/secrets/consume-from-key-vault.md, docs/features/secrets/general.md, docs/guides/running-integration-tests.md, docs/index.md
Improve & restructure documentation a bit
=> Improve & restructure documentation a bit

build/ci-build.yml
Provide note that Arcus_ServicePrincipal_AccessKey is defined in build
=> Provide note on Arcus_ServicePrincipal_AccessKey

docs/index.md, src/Arcus.Security.All/Arcus.Security.All.csproj, src/Arcus.Security.sln
Povide metapackage to pull in all things Arcus Security similar to other Arcus projects
=> Provide metapackage

build/myget-release.yml
=> Assign correct version of MyGet package

docs/auth/azure-key-vault.md, src/Arcus.Security.Providers.AzureKeyVault/Authentication/ManagedServiceIdentityAuthenticator.cs
Addresses arcus-azure/arcus.security#89
=> Added support for connection string and azure AD instance for Managed Identity auth

docs/features/key-vault/extensions/iconfiguration-integration.md
- Updated the documentation to use the `IKeyVaultAuthentication` type instead of the `IKeyVaultAuthenticator`
- Added some extra clarification regarding caching
#93
=> FIX: update SecretProvider documentation to not use obsolete types

build/myget-release.yml
Use YAML template from arcus-azure/azure-devops-templates to push preview package
=> Use YAML template from arcus-azure/azure-devops-templates to push preview package

src/Arcus.Security.Secrets.Core/Caching/CachedSecretProvider.cs, src/Arcus.Security.Secrets.Core/Interfaces/ICachedSecretProvider.cs
=> ICachedSecretProvider can return its cache-configuration

build/ci-build.yml
Use build/build-solution.yml@templates over own approach
=> Use build/build-solution.yml@templates over own approach

build/nuget-release.yml
NuGet: Use correct GitHub repo for pre-releases
=> NuGet: Use correct GitHub repo for pre-releases

docs/preview/features/secret-store/create-new-secret-provider.md, docs/preview/features/secret-store/provider/key-vault.md
=> Docs - add mentioning of caching in secret store integration

docs/preview/features/secret-store/index.md
=> Reshuffling of documentation in more logical ordering

src/Arcus.Security.All/Arcus.Security.All.csproj
=> Chore - add AzureFunctions project to .All project bundle

docs/preview/features/secret-store/provider/environment-variables.md, src/Arcus.Security.Core/Extensions/SecretStoreBuilderExtensions.cs, src/Arcus.Security.Core/Providers/EnvironmentVariableSecretProvider.cs, src/Arcus.Security.Tests.Unit/Core/IHostBuilderExtensionsTests.cs
=> Feature - add prefix to environment variable secret provider

src/Arcus.Security.Core/Arcus.Security.Core.csproj, src/Arcus.Security.Core/Extensions/IHostBuilderExtensions.cs, src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj, src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj, src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj
This PR is related to #189 
I've removed the dependencies to AspNetCore framework.
=> Remove the dependency to AspNetCore

src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj, src/Arcus.Security.Tests.Integration/Arcus.Security.Tests.Integration.csproj, src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj
=> Migrate from Polly-Signed  to Polly

src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
Increase version of Microsoft.Azure.Services.AppAuthentication to fix authentication issues.
Closes #196
=> Increase version of Microsoft.Azure.Services.AppAuthentication

docs/features/auth/azure-key-vault.md, docs/features/secrets/general.md, docs/preview/features/auth/azure-key-vault.md, docs/preview/features/secrets/general.md, docs/v1.0.0/features/auth/azure-key-vault.md, docs/v1.0.0/features/secrets/general.md, docs/v1.1.0/features/auth/azure-key-vault.md, docs/v1.1.0/features/secrets/general.md, docs/v1.2.0/features/auth/azure-key-vault.md, docs/v1.2.0/features/secrets/general.md, docs/v1.3.0/features/auth/azure-key-vault.md, docs/v1.3.0/features/secrets/general.md
=> Authenticator -> Authentication for v1.x

docs/preview/features/secret-store/index.md, src/Arcus.Security.Core/CompositeSecretProvider.cs, src/Arcus.Security.Core/Extensions/IHostBuilderExtensions.cs, src/Arcus.Security.Core/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Security.Core/SecretStoreBuilder.cs, src/Arcus.Security.Tests.Core/Stubs/SpyLogger.cs, src/Arcus.Security.Tests.Unit/Core/Extensions/IHostBuilderExtensionsTests.cs, src/Arcus.Security.Tests.Unit/Core/Extensions/IServiceCollectionExtensionsTests.cs
Adds the secret store to the `IServiceCollection` with an `.AddSecretStore` extension that adds the `ISecretProvider` component to the registered services, but then outside the .NET hosting.
Closes #214 
Closes #215
=> Feature - add secret store to IServiceCollection

docs/preview/features/secret-store/create-new-secret-provider.md, docs/preview/features/secret-store/index.md, docs/preview/features/secret-store/named-secret-providers.md, docs/preview/features/secret-store/provider/configuration.md, docs/preview/features/secret-store/provider/docker-secrets.md, docs/preview/features/secret-store/provider/environment-variables.md, docs/preview/features/secret-store/provider/hashicorp-vault.md, docs/preview/features/secret-store/provider/key-vault.md, docs/preview/features/secret-store/provider/user-secrets.md, docs/preview/features/secrets/consume-from-key-vault.md
Relates to https://github.com/arcus-azure/arcus/issues
=> Docs - add usings to code samples in feature docs

src/Arcus.Security.AzureFunctions/Arcus.Security.AzureFunctions.csproj
=> chore: Update Microsoft.Azure.Functions.Extensions to v1.1

docs/v1.4.1/features/auth/azure-key-vault.md, docs/v1.4.1/features/secret-store/create-new-secret-provider.md, docs/v1.4.1/features/secret-store/index.md, docs/v1.4.1/features/secret-store/named-secret-providers.md, docs/v1.4.1/features/secret-store/provider/configuration.md, docs/v1.4.1/features/secret-store/provider/docker-secrets.md, docs/v1.4.1/features/secret-store/provider/environment-variables.md, docs/v1.4.1/features/secret-store/provider/hashicorp-vault.md, docs/v1.4.1/features/secret-store/provider/key-vault.md, docs/v1.4.1/features/secret-store/provider/user-secrets.md, docs/v1.4.1/features/secrets/consume-from-key-vault.md, docs/v1.4.1/features/secrets/general.md, docs/v1.4.1/index.md
Publishes the v1.4.1 feature docs; although there's no difference with the v1.4 feature docs.
Is this necessary? Feel free to close this PR if not.
=> Docs - publish v1.4.1 feature docs

src/Arcus.Security.Core/CompositeSecretProvider.cs
In an initial phase, we used `"Get Secret"` as security event name, but now, we see that there may be some specific events names that are more appropriate. Invalidating secrets for example.
=> Feature - use dedicated 'Invalidate Secret' as event name for security event tracking

src/Arcus.Security.Core/Caching/CachedSecretProvider.cs, src/Arcus.Security.Core/Caching/Configuration/CacheConfiguration.cs, src/Arcus.Security.Core/Caching/SecretProviderCachingExtensions.cs
Some additional exception and type XML comments improvements + also some extra guards to fuel the paranoia.
=> Feature - add additional exception XML docs for caching

docs/v1.5.0/features/secret-store/index.md
I fixed some minor typo's in the documentation.
=> Docs: Fix code examples

docs/features/secret-store/index.md, docs/preview/features/secret-store/index.md, docs/v1.3.0/features/secret-store/index.md, docs/v1.4.0/features/secret-store/index.md, docs/v1.4.1/features/secret-store/index.md
Continuation of #260 but with a look for the other older and more recent versions.
=> Docs - fix correct secrert store variable

docs/features/secret-store/index.md, docs/preview/features/secret-store/index.md, docs/v1.5.0/features/secret-store/index.md
Describe advantages over contacting the secrets locations directly.
Closes #278
=> docs: secret store advantages

src/Arcus.Security.Core/SecretStoreBuilder.cs, src/Arcus.Security.Core/SecretStoreSource.cs, src/Arcus.Security.Providers.AzureKeyVault/Configuration/KeyVaultConfiguration.cs, src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs, src/Arcus.Security.Providers.AzureKeyVault/KeyVaultCachedSecretProvider.cs, src/Arcus.Security.Providers.DockerSecrets/DockerSecretsSecretProvider.cs, src/Arcus.Security.Providers.DockerSecrets/Extensions/SecretStoreBuilderExtensions.cs, src/Arcus.Security.Providers.UserSecrets/UserSecretsSecretProvider.cs, src/Arcus.Security.Tests.Integration/DockerSecrets/DockerSecretsProviderTests.cs, src/Arcus.Security.Tests.Integration/DockerSecrets/SecretStoreBuilderExtensionTests.cs
Improve and streamline some xml code docs, correct some argument guards checks.
=> feat: improve xml code docs + light code cleaning

docs/preview/features/secret-store/index.md, docs/preview/features/secrets/general.md, docs/versioned_docs/version-v0.1.0/features/secrets/general.md, docs/versioned_docs/version-v0.2.0/features/secrets/general.md, docs/versioned_docs/version-v0.3.0/features/secrets/general.md, docs/versioned_docs/version-v0.4.0/features/secrets/general.md, docs/versioned_docs/version-v1.0.0/features/secrets/general.md, docs/versioned_docs/version-v1.1.0/features/secrets/general.md, docs/versioned_docs/version-v1.2.0/features/secrets/general.md, docs/versioned_docs/version-v1.3.0/features/secrets/general.md, docs/versioned_docs/version-v1.4.0/features/secrets/general.md, docs/versioned_docs/version-v1.4.1/features/secrets/general.md, docs/versioned_docs/version-v1.5.0/features/secrets/general.md, docs/versioned_docs/version-v1.6.0/features/secret-store/index.md, docs/versioned_docs/version-v1.6.0/features/secrets/general.md, docs/versioned_docs/version-v1.7.0/features/secret-store/index.md, docs/versioned_docs/version-v1.7.0/features/secrets/general.md
Follow-up PR w/ small improvements regarding secret store and general secret interaction.
Closes #340
=> docs: small secret store improvs (follow-up)

src/Arcus.Security.AzureFunctions/Arcus.Security.AzureFunctions.csproj, src/Arcus.Security.Core/Arcus.Security.Core.csproj, src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj, src/Arcus.Security.Providers.CommandLine/Arcus.Security.Providers.CommandLine.csproj, src/Arcus.Security.Providers.DockerSecrets/Arcus.Security.Providers.DockerSecrets.csproj, src/Arcus.Security.Providers.HashiCorp/Arcus.Security.Providers.HashiCorp.csproj, src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj
Adds package readme project tag to the project files.
Relates to https://github.com/arcus-azure/arcus/issues/209
=> chore: add package readme project tag

src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultCachedSecretProviderTests.cs, src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs
Remove the temporary tested stored secret during the Azure Key Vault secret provider tests to not bloat the used Azure Key Vault resource.
=> test: remove temporary tested stored az keyvault secret

build/variables/test.yml, docs/preview/03-Features/secret-store/create-new-secret-provider.md, docs/preview/03-Features/secret-store/versioned-secret-provider.md, src/Arcus.Security.Core/Caching/CachedSecretProvider.cs, src/Arcus.Security.Core/CompositeSecretProvider.cs, src/Arcus.Security.Core/Extensions/ISecretProviderExtensions.cs, src/Arcus.Security.Core/IVersionedSecretProvider.cs, src/Arcus.Security.Core/SecretProviderOptions.cs, src/Arcus.Security.Core/SecretStoreBuilder.cs, src/Arcus.Security.Core/SecretStoreSource.cs, src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs, src/Arcus.Security.Providers.AzureKeyVault/KeyVaultCachedSecretProvider.cs, src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs, src/Arcus.Security.Tests.Integration/Fixture/TestConfig.cs, src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs, src/Arcus.Security.Tests.Integration/appsettings.json, src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj, src/Arcus.Security.Tests.Unit/Core/CachedSecretProviderTests.cs, src/Arcus.Security.Tests.Unit/Core/SecretProviderOptionsTests.cs, src/Arcus.Security.Tests.Unit/Core/Stubs/InMemorySecretProvider.cs, src/Arcus.Security.Tests.Unit/Core/Stubs/InMemorySecretVersionProvider.cs, src/Arcus.Security.Tests.Unit/Core/Stubs/TestSecretProviderStub.cs, src/Arcus.Security.Tests.Unit/Core/VersionedSecretTests.cs
Add support for registering multiple secret versions for a secret name on secret provider registrations.
Closes #354
=> feat: add secret version support

docs/preview/03-Features/secret-store/azure-functions.md, docs/preview/03-Features/secret-store/index.md
Fix the documentation on using the secret store within Azure Functions.
Closes #357
=> docs: correct az func secret store docs

README.md
Remove the duplicated installation section in the `README.md` as this is available on the feature documentation site and hard to main if duplicated here.
=> chore: remove installation section

src/Arcus.Security.Core/Caching/Configuration/CacheConfiguration.cs, src/Arcus.Security.Core/SecretStoreBuilder.cs, src/Arcus.Security.Core/SecretStoreSource.cs, src/Arcus.Security.Tests.Unit/Core/Extensions/IHostBuilderExtensionsTests.cs, src/Arcus.Security.Tests.Unit/Core/MutateSecretNameSecretProviderTests.cs, src/Arcus.Security.Tests.Unit/Core/MutatedSecretNameCachedSecretProviderTests.cs, src/Arcus.Security.Tests.Unit/KeyVault/Extensions/SecretStoreBuilderExtensionsTests.cs
Remove any deprecated functionality to the secret store abstraction.
Closes #304
Closes #305 
Closes #306
=> chore: remove deprecated secret store functionality
