arcus-azure/arcus.security

src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
src/Arcus.Security.Secrets.AzureKeyVault/Arcus.Security.Secrets.AzureKeyVault.csproj
src/Arcus.Security.Secrets.Core/Arcus.Security.Secrets.Core.csproj

During the build of the NuGet packages, the XML docs weren't part of the
package. Meaning no docs during development.
This commit lets the projects generate such a documentation file which
will automatically be part of the also automatically generate NuGet
package.

DOC: add XML docs to nupkg

---

src/Arcus.Security.Providers.AzureKeyVault/Authentication/Interfaces/IKeyVaultAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/Interfaces/IKeyVaultAuthenticator.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/ManagedServiceIdentityAuthenticator.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/ServicePrincipalAuthenticator.cs
src/Arcus.Security.Secrets.AzureKeyVault/CompatibleKeyVaultAuthentication.cs
src/Arcus.Security.Secrets.AzureKeyVault/KeyVaultSecretProvider.cs
src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs
src/Arcus.Security.Tests.Unit/KeyVault/Doubles/AzureKeyVaultAuthenticatorDummy.cs
src/Arcus.Security.Tests.Unit/KeyVault/Doubles/SimulatedKeyVaultClient.cs
src/Arcus.Security.Tests.Unit/KeyVault/Doubles/StubKeyVaultAuthenticator.cs
src/Arcus.Security.Tests.Unit/KeyVault/KeyVaultSecretProviderTests.cs

Because the 'IKeyVaultAuthenticator' used the concret 'KeyVaultClient',
we couldn't quite unit test the functionality.
The `KeyVaultSecretProvider` is now updated to use both the now obsolete
`IKeyVaultSecretAuthenticator` as the now new
`IKeyVaultSecretAuthentication` that uses the `IKeyVaultClient` as
return type.
This now allows reliable unit testing of the provider.
#55

 FEAT: provide flexibility in 'KeyVaultSecretProvider' by using 'IKeyVaultCient'

---

docs/auth/azure-key-vault.md
src/Arcus.Security.Providers.AzureKeyVault/Authentication/CertificateBasedAuthentication.cs
src/Arcus.Security.Tests.Unit/KeyVault/Authentication/CertificateBasedAuthenticationTests.cs

Besides client-id/client-secret; we should also provide a way to
authenticate the Key Vault client with client-id/certificate.
#10

FEAT: certificate based authenticate Key Vault client

---

src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs
src/Arcus.Security.Tests.Integration/appsettings.json

Azure uses the terminology 'ApplicationId' (as do we in code).
The environment variable, though, doesn't reflect this terminology.
Closes #61

TEST: stable transistion from 'ClientId' > 'ApplicationId' environment variable

---

docs/features/config/replace-configuration-tokens-with-isecretprovider.md
src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
src/Arcus.Security.Providers.AzureKeyVault/Configuration/ArcusConfigurationProvider.cs
src/Arcus.Security.Providers.AzureKeyVault/Configuration/ArcusConfigurationSource.cs
src/Arcus.Security.Providers.AzureKeyVault/Configuration/SecretProviderConfigurationBuilderExtensions.cs
src/Arcus.Security.Tests.Unit/Core/Stubs/InMemorySecretProvider.cs
src/Arcus.Security.Tests.Unit/KeyVault/Configuration/SecretProviderConfigurationBuilderExtensionsTests.cs

Adds an extension to the IConfigurationBuilder so we can pass-in our own
ISecretProvider when replacing configuration tokens with secret values.

FEAT: add 'ISecretProvider' with '.AddAzureKeyVault' configuration builder

---

src/Arcus.Security.Providers.AzureKeyVault/Configuration/ArcusConfigurationProvider.cs

The implementation of the `ArcusConfigurationProvider` could use a non-obsolete method instead.

REFACTOR: use the new '.GetRawSecretAsync' in Arcus configuration manager instead

---

build/myget-release.yml

When we remove this variable in the variables block in the YAML file, we can set the variable at queue-time.
Relates to #63

FIX: remove manual variable in MyGet release

---

docs/features/key-vault/extensions/iconfiguration-integration.md

To make it more obvious that there exists a more fluent way to use the caching capabilities, I've modified the documentation on how to integrate the arcus KeyVault Provider with the ASP.NET configuration.

Use fluent approach in example when adding KeyVault ConfigProvider

---

build/variables/build.yml

Random `e` apperently was added to this var which made the builds have false positives (not found tests = skipped).

Fix - $(Project) var in `build.yml`

---

src/Arcus.Security.Providers.UserSecrets/UserSecretsSecretProvider.cs

The User Secrets secret provider should return `null` as secret value and not `null` as `Task`.
FYI: this has not impact when this is used in the secret store approach bc we test for this, but if the provider is used directly, it may cause problems.

Fixup - UserSecrets should return `null` secret value

---

src/Arcus.Security.Providers.AzureKeyVault/Configuration/KeyVaultConfiguration.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs
src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs
src/Arcus.Security.Tests.Unit/KeyVault/Configuration/KeyVaultConfigurationTests.cs
src/Arcus.Security.Tests.Unit/KeyVault/KeyVaultSecretProviderTests.cs

The Azure Key Vault name and secret names can be checked on their format before we send out HTTP requests and (maybe) get some obscure return exception message.
These guards help with that and is by itself an extra safety check for malicious input.
See https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates#objects-identifiers-and-versioning

Feature - add guards against Azure Key Vault component formats

---

docs/preview/index.md

Provide link to root index page to the HashiCorp Vault secret provider.
Closes #159

Docs - add HashiCorp Vault link to index page

---

docs/preview/features/secret-store/create-new-secret-provider.md
docs/preview/features/secret-store/index.md
src/Arcus.Security.Core/SecretStoreBuilder.cs
src/Arcus.Security.Core/SecretStoreSource.cs
src/Arcus.Security.Tests.Unit/Core/IHostBuilderExtensionsTests.cs
src/Arcus.Security.Tests.Unit/Core/SecretStoreBuilderTests.cs

Provides an `SecretStoreBuilder.AddProvider` method overload that takes in the `IServiceProvider` so additional dependent services can be included when creating an `ISecretProvider`.
A good example is logging. With this change, we can now provide an `ILogger` instance to each `ISecretProvider` and consumers can also benefit from this when implementing their own provider.
- Added method overload
- Updated the `SecretStoreSource` to accompany this change (with backwards compatibility in mind, so chosen for a mutable approach)
- Updated secret store builder registration so the `IServiceProvider` gets send allong the needed registrations
- Added unit tests that also verify if caching and secret name mutation is combinable with this approach (which it does 😃 ). 
- Updated (preview) feature …

Feature - add secret providers to secret store w/ dependent services

---

docs/preview/features/secret-store/provider/hashicorp-vault.md
docs/preview/features/secret-store/provider/key-vault.md
src/Arcus.Security.Providers.HashiCorp/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.HashiCorp/HashiCorpSecretProvider.cs
src/Arcus.Security.Tests.Integration/HashiCorp/HashiCorpSecretProviderTests.cs

Add secret name mutation to all the HashiCorp Vault secret store builder so the secret name can be altered before it's send to the HashiCorp Vault.

Feature - add secret name mutation to HashiCorp Vault secret store builder extensions

---

src/Arcus.Security.Core/CompositeSecretProvider.cs

Since the `CompositeSecretProvider` is not capable of determing the correct caching configuration from the different registered `ICachedSecretProvider`s, we should throw an `NotSupportedException` instead of returning the `null` to show the consumer that this isn't available at this point.
Closes #187

Fix - throw NotSupportedException when accessing the cache config directly from the secret store

---

src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
src/Arcus.Security.Providers.AzureKeyVault/Authentication/CertificateBasedAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/IKeyVaultAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/ManagedServiceIdentityAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/ServicePrincipalAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs
src/Arcus.Security.Tests.Integration/Constants.cs
src/Arcus.Security.Tests.Integration/Fixture/TestConfig.cs
src/Arcus.Security.Tests.Integration/IntegrationTest.cs
src/Arcus.Security.Tests.Integration/KeyVault/KeyVaultSecretProviderTests.cs
src/Arcus.Security.Tests.Integration/KeyVault/SecretStoreBuilderExtensionsTests.cs
src/Arcus.Security.Tests.Integration/appsettings.json
src/Arcus.Security.Tests.Unit/Blanks.cs
src/Arcus.Security.Tests.Unit/KeyVault/KeyVaultSecretProviderTests.cs
src/Arcus.Security.Tests.Unit/KeyVault/SecretStoreBuilderExtensionsTests.cs

Provide capability to use both the 'old' as the 'new' SDK packages for interacting with the Azure Key Vault.
This includes double support in the secret provider itself, and updating the secret store builder extensions to have support for these new authentication types.
Closes #191

Feature - provide support for using new Azure.Identity SDK in Azure Key Vault secret provider

---

docs/preview/features/secret-store/index.md
src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Core/SecretStoreAuditingOptions.cs
src/Arcus.Security.Core/SecretStoreBuilder.cs
src/Arcus.Security.Tests.Core/Arcus.Security.Tests.Core.csproj
src/Arcus.Security.Tests.Core/Stubs/TestLoggerProvider.cs
src/Arcus.Security.Tests.Unit/Core/IHostBuilderExtensionsTests.cs
src/Arcus.Security.Tests.Unit/Core/SecretStoreBuilderTests.cs

Provide the capability to opt-in for the emitted security events when requesting a secret through the secret store.
This includes the extension to configure this, alongside the necessary tests and docs update.
Closes #177 
Closes #205

Feature - opt-in of security events in secret store

---

src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs

Uses the default `DefaultAzureCredential` which behind the scenes uses the managed identity and environment variables (like we chained together), but also uses the Azure CLI information to make it more dev-friendly.
Relates to #217

Fix - use default Azure TokenCredential for more dev-friendliness

---

src/Arcus.Security.AzureFunctions/Extensions/IFunctionHostBuilderExtensions.cs
src/Arcus.Security.Core/InternalsVisibleTo.cs

Because of #215  , we are now able to use the `.AddSecretStore` directly on an `IServiceCollection` instance.
This can be used within the Azure Function extension too so we don't have to expose internal functionality.

Feature - use '.AddSecretStore' in Azure Functions secret store extension

---

src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Core/SecretStoreBuilder.cs
src/Arcus.Security.Core/SecretStoreSource.cs

Since #204 we allow secret provider registrations to include a name that represents the secret source. This name can be used when we log a security even for the secret store.

Feature - use secret source name within security logging

---

src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Tests.Integration/KeyVault/SecretStoreBuilderExtensionsTests.cs
src/Arcus.Security.Tests.Unit/KeyVault/Extensions/SecretStoreBuilderExtensionsTests.cs

Provide a simplified version of each of the new SDK method overloads with only the caching as an additional option.
This lets consumers choose for a less complicated option when using the new SDK approach.
Closes #219

Feature - simplify Azure Key Vault secret store overloads

---

src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj

Updates to new version v2.0 of Arcus.Observability packae + making sure that we use the same package dependency strategy as the Observability library.
Closes #190

Feature - update to Arcus.Observability v2.0

---

src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Tests.Unit/KeyVault/Extensions/SecretStoreBuilderExtensionsTests.cs

Adds some extra overloads for the Azure Key Vault secret provider in the secret store to authenticate with Managed Identity without a `clientId`.
Closes #230

Feature - add Azure Key Vault secret store overloads w/o Managed Identity clientId

---

src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj

Was a project that still was using the 'old' packages for .NET Core 2.2 support. Updated so it's the same as the other projects in this solution.

Fix - use Microsoft.Extensions.* 3.1.8 packages for UserSecrets

---

docs/preview/features/secret-store/named-secret-providers.md
src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Core/ISecretStore.cs
src/Arcus.Security.Core/SecretStoreBuilder.cs
src/Arcus.Security.Tests.Unit/AzureFunctions/IFunctionsHostBuilderTests.cs
src/Arcus.Security.Tests.Unit/Core/Extensions/IHostBuilderExtensionsTests.cs
src/Arcus.Security.Tests.Unit/Core/Extensions/IServiceCollectionExtensionsTests.cs

Add support for registering multiple `ISecretProvider` implementations with the same name so they are combined in a subset upon retrieval.
Closes #237

Feature - support subset of secret providers in secret store

---

src/Arcus.Security.Core/Providers/EnvironmentVariableSecretProvider.cs
src/Arcus.Security.Tests.Unit/Core/EnvironmentVariableSecretProviderTests.cs

The `EnvironmentVariableSecretProvider` didn't take into account that the delegated `.GetRawSecretAsync` could return `null`. The secret store itself was handling such an exception (it was an `ArgumentException`) but this was not a correct implementation.

Fix - check raw secret result before passing allong in environment variable secret provider

---

docs/preview/features/secret-store/provider/key-vault.md
src/Arcus.Security.Core/Caching/CachedSecretProvider.cs
src/Arcus.Security.Core/Caching/Configuration/CacheConfiguration.cs
src/Arcus.Security.Core/Caching/Configuration/ICacheConfiguration.cs
src/Arcus.Security.Core/Caching/SecretProviderCachingExtensions.cs
src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs

Guide users towards the `CacheConfiguration.Default` instead of using the `allowCaching`.
Closes #239

Feature - use default `CacheConfiguration` instead of `allowCaching`

---

src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Core/Providers/MutatedSecretNameSecretProvider.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/CertificateBasedAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/ManagedServiceIdentityAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Authentication/ServicePrincipalAuthentication.cs
src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs
src/Arcus.Security.Tests.Integration/Arcus.Security.Tests.Integration.csproj
src/Arcus.Security.Tests.Integration/DockerSecrets/SecretStoreBuilderExtensionTests.cs
src/Arcus.Security.Tests.Integration/IntegrationTest.cs
src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj
src/Arcus.Security.Tests.Unit/Core/Extensions/IServiceCollectionExtensionsTests.cs

Use only verbose logging in the secret store so the consumers don't get overloaded with 'noise' from the library.
Plus killed the warnings ⚔️ 🐉 .
Closes #269

fix: use verbose logging in secret store

---

src/Arcus.Security.Core/Arcus.Security.Core.csproj

Let's use NuGet version ranges when referencing our Arcus packages so we can more easily reference multiple Arcus packages in the same project.
Relates to https://github.com/arcus-azure/arcus/issues/129

fix: use Arcus NuGet version ranges

---

docs/preview/features/secret-store/index.md
docs/preview/features/secret-store/provider/cmd-line.md
src/Arcus.Security.Providers.CommandLine/Arcus.Security.Providers.CommandLine.csproj
src/Arcus.Security.Providers.CommandLine/CommandLineSecretProvider.cs
src/Arcus.Security.Providers.CommandLine/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj
src/Arcus.Security.Tests.Unit/CommandLine/CommandLineSecretProviderTests.cs
src/Arcus.Security.Tests.Unit/CommandLine/SecretStoreBuilderExtensionsTests.cs
src/Arcus.Security.sln

Adds a new secret provider that takes in command line arguments and includes them into the secret store.
Closes #240

feat: add command line secret provider

---

src/Arcus.Security.All/Arcus.Security.All.csproj
src/Arcus.Security.AzureFunctions/Arcus.Security.AzureFunctions.csproj
src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
src/Arcus.Security.Providers.CommandLine/Arcus.Security.Providers.CommandLine.csproj
src/Arcus.Security.Providers.DockerSecrets/Arcus.Security.Providers.DockerSecrets.csproj
src/Arcus.Security.Providers.HashiCorp/Arcus.Security.Providers.HashiCorp.csproj
src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj

Let's ignore the NuGet packaging warnings about the licensing and package URL's which are obsolete.

chore: ignore packaging warnings

---

build/ci-build.yml
build/nuget-release.yml
build/variables/build.yml

Make sure that we use the latest Ubuntu version to build our library.
Relates to https://github.com/arcus-azure/arcus/issues/144

fix: use `ubuntu-latest` for build vm image

---

docs/versioned_docs/version-v1.5.0/features/auth/azure-key-vault.md

We already created a dedicated page for redirecting the old Azure Key Vault authentication page towards the secret store and the Azure Key Vault secret provider, but we didn't do this for the v1.5.0 release.
Closes #262

docs: redirect from v1.5.0 old auth az key vault

---

src/Arcus.Security.Providers.AzureKeyVault/Configuration/SecretProviderConfigurationBuilderExtensions.cs

Remove the `IConfigurationBuilder` extension that was adding secrets to the application configuration.
Closes #285

fix: deprecate the configuration extension to add secrets

---

docs/preview/features/secret-store/create-new-secret-provider.md
docs/versioned_docs/version-v1.4.0/features/secret-store/create-new-secret-provider.md
docs/versioned_docs/version-v1.4.1/features/secret-store/create-new-secret-provider.md
docs/versioned_docs/version-v1.5.0/features/secret-store/create-new-secret-provider.md
docs/versioned_docs/version-v1.6.0/features/secret-store/create-new-secret-provider.md

Fixes the table of contents for creating a new custom `ISecretProvider`.
Fixes the code sample for adding critical exceptions to your custom implementation.
Closes #290

fix: wrong toc and critical exceptions code sample

---

docs/preview/features/secret-store/create-new-secret-provider.md

Fixes the code sample for the preview feature docs.
Relates to #290

fix: preview docs with wrong critical exception code sample

---

build/variables/build.yml
src/Arcus.Security.All/Arcus.Security.All.csproj
src/Arcus.Security.AzureFunctions/Arcus.Security.AzureFunctions.csproj
src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
src/Arcus.Security.Providers.CommandLine/Arcus.Security.Providers.CommandLine.csproj
src/Arcus.Security.Providers.DockerSecrets/Arcus.Security.Providers.DockerSecrets.csproj
src/Arcus.Security.Providers.HashiCorp/Arcus.Security.Providers.HashiCorp.csproj
src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj
src/Arcus.Security.Tests.Core/Arcus.Security.Tests.Core.csproj
src/Arcus.Security.Tests.Integration/Arcus.Security.Tests.Integration.csproj
src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj

Add .NET 6 as target framework on the available projects.
Relates to https://github.com/arcus-azure/arcus/issues/106

chore: upgrade to net6.0

---

src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs

The warning message that was displayed to developers when they used the obsolete version of `AddAzureKeyVaultWithManagedServiceIdentity` was displayed as:
> Use the AddAzureKeyVaultWithServicePrincipal method overload with Default instead to allow default caching.
Seems like the `nameof(CacheConfiguration.Default)` just gets translated to `Default` and this is a bit confusing.

fix: Improve the obsolete-warning regarding default caching

---

src/Arcus.Security.Providers.AzureKeyVault/KeyVaultCachedSecretProvider.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs

In previous PR, https://github.com/arcus-azure/arcus.security/pull/324, we marked the dependency name as obsolete, while this was not correct. Only the regular expressions and the patterns should be marked as obsolete.
Relates to #317

chore: correct marking az keyvault secret name obsolete

---

build/nuget-release.yml

Since we stepped off from the `Arcus.Security.All` package, let's use a different 'default' package in the release notes.

chore: update with az keyvault as default package

---

src/Arcus.Security.AzureFunctions/Arcus.Security.AzureFunctions.csproj
src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
src/Arcus.Security.Providers.CommandLine/Arcus.Security.Providers.CommandLine.csproj
src/Arcus.Security.Providers.DockerSecrets/Arcus.Security.Providers.DockerSecrets.csproj
src/Arcus.Security.Providers.HashiCorp/Arcus.Security.Providers.HashiCorp.csproj
src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj

Adds the GitHub README file to the NuGet package generation of the projects.
Adds feature docs project URL instead of GitHub URL to NuGet package.
Relates to arcus-azure/arcus#209
Relates to arcus-azure/arcus#208

chore: add readme and project url to nuget pkg

---

src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs

Use the new `logger.LogAzureKeyVaultDependency` extension instead of the general one in the Azure Key vault secret provider.

chore: use new az keyvault dependency tracking

---

docs/preview/02-Guides/add-secret-store-with-keyvault-integration.md

Use the correct Markdown syntax to show point-based walkthrough in user guide for Arcus secret store with Azure Key Vault integration.

fix: update w/ correct pointers in user guide

---

src/Arcus.Security.Core/Extensions/ISecretProviderExtensions.Deprecated.cs
src/Arcus.Security.Tests.Unit/Core/VersionedSecretTests.cs

Use the `Arcus.Security.Core` namespace so that consumers discover these extensions quicker.
Closes #364

fix: use correct namespace for versioned secret extensions

---

src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Tests.Unit/Core/VersionedSecretTests.cs

When no versioned secret provider is registered, the secret store should still run through all the registered secret providers to find a secret value.
Closes #380

fix: get versioned secrets should run though all non-versioned secret providers (❗)

---

.github/workflows/codeql-analysis.yml

Use default `main` branch in CodeQL workflow.
Relates to https://github.com/arcus-azure/arcus/issues/169

chore: use main branch in codeql

---

build/ci-build.yml
build/nuget-release.yml
build/templates/run-integration-tests.yml
build/variables/build.yml
src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Tests.Integration/Arcus.Security.Tests.Integration.csproj
src/Arcus.Security.Tests.Integration/IntegrationTest.cs

Upgrade the projects to use Arcus Observability v3.0.

chore: upgrade to observability v3.0

---

src/Arcus.Security.Core/SecretStoreBuilder.cs

More than was needed, was removed from the XML docs' (`<remarks/>`) for the updated `AddProvider` overloads.
This PR reverts the `<remarks/>` with using the newly added overloads, instead.

chore: revert secret store xml docs for 'add provider'

---

src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Core/Caching/CachedSecretProvider.cs
src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Core/CriticalExceptionFilter.cs
src/Arcus.Security.Core/Secret.cs
src/Arcus.Security.Core/SecretNotFoundException.cs
src/Arcus.Security.Core/SecretProviderOptions.cs
src/Arcus.Security.Core/SecretStoreBuilder.cs
src/Arcus.Security.Core/SecretStoreSource.cs
src/Arcus.Security.Providers.AzureKeyVault/Configuration/ArcusConfigurationProvider.cs
src/Arcus.Security.Providers.AzureKeyVault/Configuration/KeyVaultConfiguration.cs
src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultCachedSecretProvider.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs
src/Arcus.Security.Tests.Unit/KeyVault/Configuration/KeyVaultConfigurationTests.cs

Remove the `Guard.Net` package from the core and Azure Key vault secret provider projects.
Relates to #434

chore: remove guard.net from core and keyvault secret provider

---

src/Arcus.Security.Providers.CommandLine/CommandLineSecretProvider.cs
src/Arcus.Security.Providers.CommandLine/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.DockerSecrets/DockerSecretsSecretProvider.cs
src/Arcus.Security.Providers.DockerSecrets/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.HashiCorp/Configuration/HashiCorpVaultKubernetesOptions.cs
src/Arcus.Security.Providers.HashiCorp/Configuration/HashiCorpVaultOptions.cs
src/Arcus.Security.Providers.HashiCorp/Configuration/HashiCorpVaultUserPassOptions.cs
src/Arcus.Security.Providers.HashiCorp/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.HashiCorp/HashiCorpSecretProvider.cs
src/Arcus.Security.Providers.UserSecrets/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.UserSecrets/UserSecretsSecretProvider.cs

Remove the Guard.NET package references from the other secret provider projects.
Relates to #434

chore: remove guard.net from other secret providers

---

.github/workflows/code-coverage.yml
.github/workflows/codeql-analysis.yml
build/variables/build.yml
src/Arcus.Security.Core/Arcus.Security.Core.csproj
src/Arcus.Security.Providers.AzureKeyVault/Arcus.Security.Providers.AzureKeyVault.csproj
src/Arcus.Security.Providers.CommandLine/Arcus.Security.Providers.CommandLine.csproj
src/Arcus.Security.Providers.DockerSecrets/Arcus.Security.Providers.DockerSecrets.csproj
src/Arcus.Security.Providers.HashiCorp/Arcus.Security.Providers.HashiCorp.csproj
src/Arcus.Security.Providers.UserSecrets/Arcus.Security.Providers.UserSecrets.csproj
src/Arcus.Security.Tests.Core/Arcus.Security.Tests.Core.csproj
src/Arcus.Security.Tests.Integration/Arcus.Security.Tests.Integration.csproj
src/Arcus.Security.Tests.Unit/Arcus.Security.Tests.Unit.csproj

Adds .NET 10 support throughout the solution mostly for more easily migration to .NET 10 without already removing Arcus in one go.

chore(net10.0): add support for .net 10.0 throughout

---

src/Arcus.Security.Core/ISecretProvider.cs
src/Arcus.Security.Providers.CommandLine/CommandLineSecretProvider.cs

Internally implement the new `ISecretProvider` interface in the command line provider as preparation for the migration, without too much changes at once.

chore(cmd.line): internally implement new secret provider for cmd line

---

src/Arcus.Security.Core/Caching/CachedSecretProvider.cs
src/Arcus.Security.Core/Caching/Configuration/ICacheConfiguration.cs
src/Arcus.Security.Core/Caching/ICachedSecretProvider.cs
src/Arcus.Security.Core/Extensions/ISecretProviderExtensions.cs
src/Arcus.Security.Core/ISecretProvider.cs
src/Arcus.Security.Core/ISyncSecretProvider.cs
src/Arcus.Security.Core/IVersionedSecretProvider.cs
src/Arcus.Security.Core/Providers/ConfigurationSecretProvider.cs
src/Arcus.Security.Core/Providers/EnvironmentVariableSecretProvider.cs
src/Arcus.Security.Core/Secret.cs
src/Arcus.Security.Core/SecretNotFoundException.cs
src/Arcus.Security.Core/SecretProviderOptions.cs
src/Arcus.Security.Core/SecretStoreBuilder.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs
src/Arcus.Security.Providers.CommandLine/CommandLineSecretProvider.cs
src/Arcus.Security.Providers.DockerSecrets/DockerSecretsSecretProvider.cs
src/Arcus.Security.Providers.HashiCorp/Extensions/SecretStoreBuilderExtensions.cs
src/Arcus.Security.Providers.HashiCorp/HashiCorpSecretProvider.cs
src/Arcus.Security.Providers.UserSecrets/UserSecretsSecretProvider.cs

Now that all the implementations have updated their deprecated/new extensions, we can safely deprecate the abstractions itself in the core package.
Relates to #438

chore(core): deprecate remaining core functionality

---

src/Arcus.Security.Core/CompositeSecretProvider.cs
src/Arcus.Security.Core/ISecretProvider.cs
src/Arcus.Security.Core/Providers/ConfigurationSecretProvider.cs
src/Arcus.Security.Core/Providers/EnvironmentVariableSecretProvider.cs
src/Arcus.Security.Core/SecretStoreBuilder.cs
src/Arcus.Security.Providers.AzureKeyVault/KeyVaultSecretProvider.cs
src/Arcus.Security.Providers.CommandLine/CommandLineSecretProvider.cs
src/Arcus.Security.Providers.DockerSecrets/DockerSecretsSecretProvider.cs
src/Arcus.Security.Providers.HashiCorp/HashiCorpSecretProvider.cs
src/Arcus.Security.Providers.UserSecrets/UserSecretsSecretProvider.cs

Make sure that all failed versions of the `SecretResult` model also includes the secret name for better tracability/defect localization. It also makes more sense that this information is always available.
Follow-up on #460

chore(core): make secret result name always available
